import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header, { navItem } from "@/components/shared/Header";
import { FloatingNav } from "@/components/ui/NavBar";
import { auth } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col items-center w-screen min-h-screen overflow-x-hidden relative bg-slate-800`}>
        <Header />
        <FloatingNav userId={session?.user.id} userImage={session?.user.image} navItems={navItem}/>
        {children}
      </body>
    </html>
  );
}
